apiVersion: v1
kind: ConfigMap
metadata:
  name: beckn-config
  namespace: villagestay
data:
  default.yml: |
    app:
      port: 8080
      gateway:
        mode: bap
        inMemory: false
      privateKey: "your-private-key"
      publicKey: "your-public-key"
      subscriberId: "villagestay.com"
      subscriberUrl: "https://beckn.villagestay.com"
      registryUrl: "https://registry.beckn.org"
      auth: true
      uniqueKey: "your-unique-key"
      city: "std:080"
      country: "IND"
      ttl: "PT30M"
      httpTimeout: 3000
      httpRetryCount: 2
      
    database:
      host: postgres-service
      port: 5432
      database: beckn
      username: postgres
      password: password
      
    redis:
      host: redis-service
      port: 6379
      ttl: 600
      
    responseCache:
      mongoURL: ""
      ttl: 10
      
    telemetry:
      enabled: false
      url: ""
      batchSize: 100
      syncInterval: 60
      
    logging:
      level: "info"
      
    monitoring:
      enabled: true
      port: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beckn-deployment
  namespace: villagestay
  labels:
    app: beckn
    tier: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: beckn
      tier: gateway
  template:
    metadata:
      labels:
        app: beckn
        tier: gateway
    spec:
      containers:
      - name: beckn-gateway
        image: beckn/protocol-server:latest
        ports:
        - containerPort: 8080
        - containerPort: 9090
        envFrom:
        - configMapRef:
            name: villagestay-config
        - secretRef:
            name: villagestay-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        volumeMounts:
        - name: beckn-config
          mountPath: /app/config/default.yml
          subPath: default.yml
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: beckn-config
        configMap:
          name: beckn-config
      imagePullSecrets:
      - name: registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: beckn-service
  namespace: villagestay
  labels:
    app: beckn
spec:
  selector:
    app: beckn
    tier: gateway
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: metrics
    protocol: TCP
    port: 9090
    targetPort: 9090
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: beckn-ingress
  namespace: villagestay
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - beckn.villagestay.com
    secretName: beckn-tls-secret
  rules:
  - host: beckn.villagestay.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: beckn-service
            port:
              number: 8080