apiVersion: v1
kind: Secret
metadata:
  name: villagestay-secrets
  namespace: villagestay
type: Opaque
data:
  # Base64 encoded values (replace with actual encoded secrets)
  DATABASE_PASSWORD: cGFzc3dvcmQ=  # password
  JWT_SECRET: eW91ci1qd3Qtc2VjcmV0LWtleQ==  # your-jwt-secret-key
  BECKN_API_KEY: eW91ci1iZWNrbi1hcGkta2V5  # your-beckn-api-key
  GEMINI_API_KEY: eW91ci1nZW1pbmktYXBpLWtleQ==  # your-gemini-api-key
  BLOCKCHAIN_PRIVATE_KEY: eW91ci1ibG9ja2NoYWluLXByaXZhdGUta2V5  # your-blockchain-private-key
  REDIS_PASSWORD: cmVkaXMtcGFzc3dvcmQ=  # redis-password
  RABBITMQ_PASSWORD: cmFiYml0bXEtcGFzc3dvcmQ=  # rabbitmq-password
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: villagestay
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTi... # Base64 encoded TLS certificate
  tls.key: LS0tLS1CRUdJTi... # Base64 encoded TLS private key